version: "3.7"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_image: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: melancia
    volumes:
      - ./home/con-jifs/db/data:/var/lib/mysql
    restart: always
  api:
    build: "./con-jifs"
    container_name: java-container
    restart: always
    volumes:
      - ./home/con-jifs:/home/java/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  web:
    image: "php:7.2-apache"
    container_name: php-container
    restart: always
    volumes:
      - ./home/web:/var/www/html
    ports:
      - "8888:80"
    depends_on:
      - db
      - api