version: '3'
services:
  web-server:
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - ./web:/var/www/html/
    ports:
      - 8000:80

  mysql:
   container_name: mysql-db
   image: mysql/mysql-server:8.0
   environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=conjifs
      - MYSQL_USER=marcos
      - MYSQL_PASSWORD=12345678
   ports:
   - "3306:3306"
   restart: always

  api:
    build: .
    links:
      - mysql
    container_name: conjifs
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_PORT=3306
      - DB_NAME=conjifs
      - DB_HOST=mysql
      - MYSQL_USER=marcos
      - MYSQL_USER_PASSWORD=12345678
    depends_on:
      - mysql