version: '3'
networks:
  monitor:
    internal: true
services:
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        volumes:
            - ./volume:/var/lib/grafana
        restart: always
        ports:
            - 3000:3000
        networks:
            - monitor

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - 9090:9090
        restart: always
        networks:
            - monitor


    web-server:
        container_name: php-apache
        image: php:8.0-apache
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8000:80
            
    springboot-app:
        image: springboot-app
        links:
            - mysql
        ports:
            - 8080:8080
        build: ../con-jifs/
        depends_on:
            - db
        
    db:
        image: mysql:5.7
        container_name: mysql
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 
            MYSQL_DATABASE: conjifs
            MYSQL_USER: root
            MYSQL_PASSWORD:

volumes:
  prometheus_data: