- hosts: localhost
  become: true
  handlers:
  tasks:

    - name: Atualiza pacotes do repositorio
      apt:
        upgrade: dist

    - name: Instala docker-compose
      apt:
        name: docker-compose
        state: latest

    - name: Cria diretorio de aplicações e copia arquivos
      shell: mkdir /apt/ && mkdir /apt/volume && chmod 777 /apt/volume && cp /vagrant/docker-compose.yml /apt/ 

    - name: Executa deploy
      shell: docker-compose up -d --force-recreate
      args:
        chdir: /apt/
