Vagrant.configure("2") do |geral|
  geral.vm.box = "ebruno/ansible-docker"
  geral.vm.box_version = "0.1"
  geral.vm.provider "virtualbox" do |memory|
    memory.memory = 2048
    memory.cpus = 3
  end

  geral.vm.define "server" do |server|
    server.vm.provider "virtualbox" do |name|
        name.name = "Servidor"
    end
    server.vm.network "forwarded_port", guest: 3000, host: 3000
    server.vm.network "forwarded_port", guest: 9090, host: 9090
    server.vm.provision "shell", 
      inline: "ansible-playbook /vagrant/playbook.yml"
  end
end